apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: myfirstkube
  labels:
    app: mykube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mykube
  template:
    metadata:
      labels:
        app: mykube
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
